import type { Metadata } from 'next';
import { Geist, Geist_Mono, IBM_Plex_Sans } from 'next/font/google';
import './globals.css';


const ibmPlexSans = IBM_Plex_Sans({
	variable: '--font-IBM_PLEX-sans',
	subsets: ['latin'],
});

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${ibmPlexSans.variable}antialiased`}
			>
				<div className='grow md:overflow-y-auto w-full ml-52 min-h-screen px-24 py-8'>
					{children}
				</div>
			</body>
		</html>
	);
}
